site_name: Quinn

theme:
  name: material

plugins:
  - search
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - section-index
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: sphinx
            docstring_options:
              show_if_no_docstring: true
            show_source: true
  - mkdocs-jupyter

nav:
  - Home: index.md
  - Usage: usage.md
  - API Reference: reference/SUMMARY.md
  - Examples:
    - "examples/index.md"
    - "notebooks/schema_as_code.ipynb"
  - Learn more: 
    - learn_more/index.md
    - learn_more/column_to_list.md


markdown_extensions:
    - markdown_include.include:
        base_path: docs
    - attr_list
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg