[tool.poetry]
name = "quinn"
version = "0.10.0"
description = "Pyspark helper methods to maximize developer efficiency"
authors = ["MrPowers <matthewkevinpowers@gmail.com>"]
license = "Apache-2.0"
readme = "README.md"
homepage = "https://github.com/MrPowers/quinn/"
keywords = ['apachespark', 'spark', 'pyspark']

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

###########################################################################
#                         MAIN DEPENDENCIES
###########################################################################

[tool.poetry.dependencies]
python = ">=3.7,<4.0"


###########################################################################
#                         DEPENDENCY GROUPS 
###########################################################################

[tool.poetry.group.development]
optional = true

[tool.poetry.group.docs]
optional = true

[tool.poetry.group.testing]
optional = true

[tool.poetry.group.linting]
optional = true

[tool.poetry.group.development.dependencies]
pyspark = ">2"
semver = "^3"

[tool.poetry.group.testing.dependencies]
pytest = "^7"
chispa = "^0.9"
pytest-describe = "^2"

[tool.poetry.group.linting.dependencies]
ruff = "^0.0.291"

[tool.poetry.group.docs.dependencies]
mkdocstrings-python = "^0.8.3"
mkdocs-gen-files = "^0.4.0"
mkdocs-literate-nav = "^0.6.0"
mkdocs-section-index = "^0.3.5"
markdown-include = "^0.8.1"
mkdocs = "^1.4.2"

###########################################################################
#                         LINTING CONFIGURATION 
###########################################################################

[tool.ruff]
line-length = 150
ignore = ["D100"]
required-version = "0.0.291"