name: Flake8 check

on:
  push:
    branches:
    - feat/add-flake8 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.5
      uses: actions/setup-python@v2
      with:
        python-version: 3.5.10
    - name: flake8 Lint
      uses: py-actions/flake8@v2
      with:
        max-line-length: "150"
        plugins: "flake8-bugbear==22.12.6 pep8-naming flake8-pyproject"
