name: Lint

on: push 

jobs:
  precommit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Run pre-commit hooks
        run: |
          pip install pre-commit
          pre-commit install
          pre-commit run -a
