name: MKDocs deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Set up Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.4.0
      - name: Install dependencies
        run:
          poetry install --with mkdocs
      - name: Setup GH
        run:
          git config user.name 'github-actions[bot]' && \
          git config user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Build and Deploy
        run:
          poetry run mkdocs gh-deploy
